<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW7112" ignored="0" name="TestsWithFactoryForCircle" tests="15" failures="6" timestamp="06 фев 2019 07:08:49 GMT" time="0.173" errors="0">
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [118.438] but found [18.85]">
      <![CDATA[java.lang.AssertionError: expected [118.438] but found [18.85]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:24)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [118.438] but found [-18.85]">
      <![CDATA[java.lang.AssertionError: expected [118.438] but found [-18.85]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:24)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.002" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [140.146] but found [-22.305]">
      <![CDATA[java.lang.AssertionError: expected [140.146] but found [-22.305]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:24)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircumference" time="0.01" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [140.146] but found [22.305]">
      <![CDATA[java.lang.AssertionError: expected [140.146] but found [22.305]
at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:24)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [28.274]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [28.274]
at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:31)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [0.0] but found [39.592]">
      <![CDATA[java.lang.AssertionError: expected [0.0] but found [39.592]
at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:31)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.03" classname="jar.circle.TestsForCircle"/>
</testsuite> <!-- TestsWithFactoryForCircle -->
