<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW7112" name="TestsWithDataProviderForRectangle" tests="44" failures="20" timestamp="6 Feb 2019 15:43:21 GMT" time="0.022" errors="0">
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [114.917372] but found [115.917372]">
      <![CDATA[java.lang.AssertionError: expected [114.917372] but found [115.917372]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-11921.264] but found [11936.972]">
      <![CDATA[java.lang.AssertionError: expected [-11921.264] but found [11936.972]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-6445.49] but found [13217.26]">
      <![CDATA[java.lang.AssertionError: expected [-6445.49] but found [13217.26]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-176.0] but found [182.0]">
      <![CDATA[java.lang.AssertionError: expected [-176.0] but found [182.0]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-16.0] but found [16.0]">
      <![CDATA[java.lang.AssertionError: expected [-16.0] but found [16.0]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-8454.4554] but found [16908.9108]">
      <![CDATA[java.lang.AssertionError: expected [-8454.4554] but found [16908.9108]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [52.00000000000001] but found [52.00000000000002]">
      <![CDATA[java.lang.AssertionError: expected [52.00000000000001] but found [52.00000000000002]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [6.0] but found [8.0]">
      <![CDATA[java.lang.AssertionError: expected [6.0] but found [8.0]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [168.78] but found [225.1]">
      <![CDATA[java.lang.AssertionError: expected [168.78] but found [225.1]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetPerimeter" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [1.5E-12] but found [2.0E-12]">
      <![CDATA[java.lang.AssertionError: expected [1.5E-12] but found [2.0E-12]
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetPerimeter -->
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetRectangle" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-31223.576999999997] but found [31223.576999999997]">
      <![CDATA[java.lang.AssertionError: expected [-31223.576999999997] but found [31223.576999999997]
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-356420.115] but found [4.29581930625E7]">
      <![CDATA[java.lang.AssertionError: expected [-356420.115] but found [4.29581930625E7]
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-0.0] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [-0.0] but found [0.0]
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [-0.0] but found [7.147781611058918E7]">
      <![CDATA[java.lang.AssertionError: expected [-0.0] but found [7.147781611058918E7]
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [3166.8736] but found [3171.9424]">
      <![CDATA[java.lang.AssertionError: expected [3166.8736] but found [3171.9424]
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testIsQuadrate -->
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testIsQuadrate -->
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testIsQuadrate -->
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testIsQuadrate -->
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testIsQuadrate -->
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
  <testcase name="testIsQuadrate" time="0.0" classname="jar.rectangle.TestsForRectangle"/>
</testsuite> <!-- TestsWithDataProviderForRectangle -->
