<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPRURYAW7112" name="TestsWithFactoryForCircle" tests="15" failures="6" timestamp="6 Feb 2019 15:28:49 GMT" time="0.016" errors="0">
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircle" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [-22.305] but found [140.146]">
      <![CDATA[java.lang.AssertionError: expected [-22.305] but found [140.146]
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [18.85] but found [118.438]">
      <![CDATA[java.lang.AssertionError: expected [18.85] but found [118.438]
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [-18.85] but found [118.438]">
      <![CDATA[java.lang.AssertionError: expected [-18.85] but found [118.438]
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [22.305] but found [140.146]">
      <![CDATA[java.lang.AssertionError: expected [22.305] but found [140.146]
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetCircumference -->
  <testcase name="testGetCircumference" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [39.592] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [39.592] but found [0.0]
	at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.016" classname="jar.circle.TestsForCircle">
    <failure type="java.lang.AssertionError" message="expected [28.274] but found [0.0]">
      <![CDATA[java.lang.AssertionError: expected [28.274] but found [0.0]
	at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testGetSquare -->
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
  <testcase name="testGetSquare" time="0.0" classname="jar.circle.TestsForCircle"/>
</testsuite> <!-- TestsWithFactoryForCircle -->
