<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="TestSuite" time="0.048" tests="75" errors="0" skipped="0" failures="30">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name="sun.boot.library.path" value="C:\Program Files\Java\jdk1.8.0_191\jre\bin"/>
    <property name="java.vm.version" value="25.191-b12"/>
    <property name="user.country.format" value="RU"/>
    <property name="java.vm.vendor" value="Oracle Corporation"/>
    <property name="maven.multiModuleProjectDirectory" value="C:\Users\Maria_Kuznetsova1\eclipse-workspace\simple"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="path.separator" value=";"/>
    <property name="guice.disable.misplaced.annotation.check" value="true"/>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="user.script" value=""/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.os.patch.level" value=""/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="user.dir" value="C:\Users\Maria_Kuznetsova1\eclipse-workspace\simple"/>
    <property name="java.runtime.version" value="1.8.0_191-b12"/>
    <property name="java.awt.graphicsenv" value="sun.awt.Win32GraphicsEnvironment"/>
    <property name="java.endorsed.dirs" value="C:\Program Files\Java\jdk1.8.0_191\jre\lib\endorsed"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.io.tmpdir" value="C:\Users\MARIA_~1\AppData\Local\Temp\"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="user.variant" value=""/>
    <property name="os.name" value="Windows 10"/>
    <property name="classworlds.conf" value="C:\Program Files\Maven\apache-maven-3.6.0\bin\..\bin\m2.conf"/>
    <property name="sun.jnu.encoding" value="Cp1251"/>
    <property name="java.library.path" value="C:\Program Files\Java\jdk1.8.0_191\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\Program Files\Java\jdk1.8.0_191\bin;C:\Program Files\Maven\apache-maven-3.6.0\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;."/>
    <property name="maven.conf" value="C:\Program Files\Maven\apache-maven-3.6.0\bin\../conf"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="java.class.version" value="52.0"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="os.version" value="10.0"/>
    <property name="library.jansi.path" value="C:\Program Files\Maven\apache-maven-3.6.0\bin\..\lib\jansi-native"/>
    <property name="user.home" value="C:\Users\Maria_Kuznetsova1"/>
    <property name="user.timezone" value="Europe/Moscow"/>
    <property name="java.awt.printerjob" value="sun.awt.windows.WPrinterJob"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="file.encoding" value="Cp1251"/>
    <property name="user.name" value="Maria_Kuznetsova1"/>
    <property name="java.class.path" value="C:\Program Files\Maven\apache-maven-3.6.0\bin\..\boot\plexus-classworlds-2.5.2.jar"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.home" value="C:\Program Files\Java\jdk1.8.0_191\jre"/>
    <property name="sun.java.command" value="org.codehaus.plexus.classworlds.launcher.Launcher clean install"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="user.language" value="en"/>
    <property name="user.language.format" value="ru"/>
    <property name="awt.toolkit" value="sun.awt.windows.WToolkit"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.version" value="1.8.0_191"/>
    <property name="java.ext.dirs" value="C:\Program Files\Java\jdk1.8.0_191\jre\lib\ext;C:\WINDOWS\Sun\Java\lib\ext"/>
    <property name="sun.boot.class.path" value="C:\Program Files\Java\jdk1.8.0_191\jre\lib\resources.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\rt.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\sunrsasign.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jsse.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jce.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\charsets.jar;C:\Program Files\Java\jdk1.8.0_191\jre\lib\jfr.jar;C:\Program Files\Java\jdk1.8.0_191\jre\classes"/>
    <property name="sun.stderr.encoding" value="cp866"/>
    <property name="java.vendor" value="Oracle Corporation"/>
    <property name="maven.home" value="C:\Program Files\Maven\apache-maven-3.6.0\bin\.."/>
    <property name="file.separator" value="\"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="sun.stdout.encoding" value="cp866"/>
    <property name="sun.desktop" value="windows"/>
    <property name="sun.cpu.isalist" value="amd64"/>
  </properties>
  <testcase name="testGetQuadrate" classname="jar.quadrate.TestsForQuadrate" time="0.016"/>
  <testcase name="testGetPerimeter" classname="jar.quadrate.TestsForQuadrate" time="0.016">
    <failure message="expected [-106.376] but found [106.376]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-106.376] but found [106.376]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.quadrate.TestsForQuadrate.testGetPerimeter(TestsForQuadrate.java:24)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetQuadrate" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.quadrate.TestsForQuadrate" time="0">
    <failure message="expected [-12.0] but found [12.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-12.0] but found [12.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.quadrate.TestsForQuadrate.testGetPerimeter(TestsForQuadrate.java:24)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetQuadrate" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.quadrate.TestsForQuadrate" time="0">
    <failure message="expected [0.0] but found [-1.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [0.0] but found [-1.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.quadrate.TestsForQuadrate.testGetPerimeter(TestsForQuadrate.java:24)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetQuadrate" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetSquare" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetQuadrate" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testGetSquare" classname="jar.quadrate.TestsForQuadrate" time="0"/>
  <testcase name="testForFailing" classname="jar.ExpectedExeption" time="0">
    <failure message="&#10;Method ExpectedExeption.testForFailing(double)[pri:0, instance:jar.ExpectedExeption@4b2bac3f] should have thrown an exception of class java.lang.Exception" type="org.testng.TestException">org.testng.TestException: 
Method ExpectedExeption.testForFailing(double)[pri:0, instance:jar.ExpectedExeption@4b2bac3f] should have thrown an exception of class java.lang.Exception
	at org.testng.internal.Invoker.handleInvocationResults(Invoker.java:1512)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:754)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:178)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:92)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:159)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:87)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
</failure>
  </testcase>
  <testcase name="testGetCircle" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetCircle" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetCircle" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetCircle" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetCircle" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetCircumference" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [-22.305] but found [140.146]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-22.305] but found [140.146]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
</failure>
  </testcase>
  <testcase name="testGetCircumference" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [18.85] but found [118.438]" type="java.lang.AssertionError">java.lang.AssertionError: expected [18.85] but found [118.438]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
</failure>
  </testcase>
  <testcase name="testGetCircumference" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [-18.85] but found [118.438]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-18.85] but found [118.438]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
</failure>
  </testcase>
  <testcase name="testGetCircumference" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [22.305] but found [140.146]" type="java.lang.AssertionError">java.lang.AssertionError: expected [22.305] but found [140.146]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetCircumference(TestsForCircle.java:26)
</failure>
  </testcase>
  <testcase name="testGetCircumference" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetSquare" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [39.592] but found [0.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [39.592] but found [0.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetSquare" classname="jar.circle.TestsForCircle" time="0">
    <failure message="expected [28.274] but found [0.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [28.274] but found [0.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.circle.TestsForCircle.testGetSquare(TestsForCircle.java:34)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetSquare" classname="jar.circle.TestsForCircle" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [114.917372] but found [115.917372]" type="java.lang.AssertionError">java.lang.AssertionError: expected [114.917372] but found [115.917372]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-11921.264] but found [11936.972]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-11921.264] but found [11936.972]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-6445.49] but found [13217.26]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-6445.49] but found [13217.26]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-176.0] but found [182.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-176.0] but found [182.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-16.0] but found [16.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-16.0] but found [16.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-8454.4554] but found [16908.9108]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-8454.4554] but found [16908.9108]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [52.00000000000001] but found [52.00000000000002]" type="java.lang.AssertionError">java.lang.AssertionError: expected [52.00000000000001] but found [52.00000000000002]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [6.0] but found [8.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [6.0] but found [8.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [168.78] but found [225.1]" type="java.lang.AssertionError">java.lang.AssertionError: expected [168.78] but found [225.1]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetPerimeter" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [1.5E-12] but found [2.0E-12]" type="java.lang.AssertionError">java.lang.AssertionError: expected [1.5E-12] but found [2.0E-12]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetPerimeter(TestsForRectangle.java:22)
</failure>
  </testcase>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetRectangle" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-31223.576999999997] but found [31223.576999999997]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-31223.576999999997] but found [31223.576999999997]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-356420.115] but found [4.29581930625E7]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-356420.115] but found [4.29581930625E7]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-0.0] but found [0.0]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-0.0] but found [0.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [-0.0] but found [7.147781611058918E7]" type="java.lang.AssertionError">java.lang.AssertionError: expected [-0.0] but found [7.147781611058918E7]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [3166.8736] but found [3171.9424]" type="java.lang.AssertionError">java.lang.AssertionError: expected [3166.8736] but found [3171.9424]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:165)
	at jar.rectangle.TestsForRectangle.testGetSquare(TestsForRectangle.java:29)
</failure>
  </testcase>
  <testcase name="testGetSquare" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
</failure>
  </testcase>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
</failure>
  </testcase>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
</failure>
  </testcase>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
</failure>
  </testcase>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">java.lang.AssertionError: expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:286)
	at org.testng.Assert.assertEquals(Assert.java:296)
	at jar.rectangle.TestsForRectangle.testIsQuadrate(TestsForRectangle.java:36)
</failure>
  </testcase>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0"/>
  <testcase name="testIsQuadrate" classname="jar.rectangle.TestsForRectangle" time="0.016"/>
</testsuite>